services:
  - type: web
    name: superbot-merc
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: superbot-postgres
          property: connectionString
      - key: MASTER_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: AUTH_PASSWORD
        generateValue: true

databases:
  - name: superbot-postgres
    plan: free
    region: frankfurt
